import{a as w,S as v,i as b}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const E="47437429-8394b140d2acf6ca490e5d99d",I="https://pixabay.com/api/";async function p(e,t=1,n=15){try{return(await w.get(I,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}})).data}catch{throw new Error("Failed to fetch images from the API.")}}const f=document.getElementById("gallery"),m=document.getElementById("loading");let h;function g(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}function L(e){const t=e.map(n=>`
    <li>
      <a href="${n.largeImageURL}">
        <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
        <div class="info">
          <p><span>Likes:</span> <span class="value">${n.likes}</span></p>
          <p><span>Views:</span> <span class="value">${n.views}</span></p>
          <p><span>Comments:</span> <span class="value">${n.comments}</span></p>
          <p><span>Downloads:</span> <span class="value">${n.downloads}</span></p>
        </div>
      </a>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),h?h.refresh():h=new v("#gallery a")}function a(e){b.error({title:"Error",message:e,timeout:5e3,position:"topRight"})}function P(){f.innerHTML=""}const B=document.getElementById("search-form"),S=document.getElementById("search-input"),o=document.createElement("button");o.textContent="Load more";o.classList.add("hidden","load-more");document.querySelector(".container").appendChild(o);let l=1;const d=15;let c="";B.addEventListener("submit",async e=>{if(e.preventDefault(),c=S.value.trim(),!c){a("Please enter a search term.");return}P(),l=1,g();try{const t=await p(c,l,d);t.hits.length===0?(a("Sorry, there are no images matching your search query. Please try again!"),o.classList.add("hidden")):(L(t.hits),t.hits.length<d?o.classList.add("hidden"):o.classList.remove("hidden"))}catch{a("An error occurred while fetching images.")}finally{y()}});o.addEventListener("click",async()=>{l+=1,g();try{const e=await p(c,l,d);(e.hits.length===0||e.hits.length<d)&&(o.classList.add("hidden"),a("We're sorry, but you've reached the end of search results.")),L(e.hits),A()}catch{a("An error occurred while fetching more images.")}finally{y()}});function A(){var t,n;const e=((n=(t=document.querySelector(".gallery li"))==null?void 0:t.getBoundingClientRect())==null?void 0:n.height)||0;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
